steps:
  # build the application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/gateway:latest', '.']
  # push the image to artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/gateway:latest']
  # deploy the application in cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gateway'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/gateway:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--ingress'
      - 'internal-and-cloud-load-balancing'
      - '--memory'
      - '512Mi'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'

timeout: 1200s
images: ['gcr.io/${PROJECT_ID}/gateway:latest']
